commandsperpattern:
    .css: cc css-js
    .html.twig: cc render
    .inc: cc plugin
    .info.yml: cr
    .js: cc css-js
    .links.menu.yml: cr
    .module: cc plugin
    .permissions.yml: cr
    .php: cc plugin
    .routing.yml: cr
    .services.yml: cr
    .theme: cc theme-registry
    .twig: cc render
    .yml: cc plugin
debounce: 800
drupalroot: docroot
drushargs:
    - --quiet
    - --no-ansi
drushcmd: null
drushcommand: cr
eventbuffersize: 500
excludepatterns: []
lintcommands:
    .php: php -l
    .yaml: yaml
    .yml: yaml
notify: false
patterns:
    - .html.twig
    - .twig
    - .inc
    - .yml
    - .module
    - .theme
    - .php
    - .info.yml
    - .services.yml
    - .routing.yml
    - .permissions.yml
    - .links.menu.yml
    - .css
    - .js
phpcsstandard: ""
pollinterval: 2000
postclearcommands: []
routes:
    - docroot/modules/custom
    - docroot/themes/custom
showlogo: true
sites: []
skiplint: false
watchmode: ""
